-- =============================================================================
-- VISTA_PNL_PREPARADO  —  per-company views + REPORTES umbrella
-- =============================================================================
-- Mirrors the topology of the existing VISTA_ANALISIS_CECOS:
--
--     REPORTES.VISTA_PNL_PREPARADO   = UNION ALL of the four per-CIA views
--     [FIBERLINE].VISTA_PNL_PREPARADO   selects from [FIBERLINE].VISTA_ANALISIS_CECOS
--     [FIBERTECH].VISTA_PNL_PREPARADO   ... etc.
--
-- Design intent: this view ENRICHES rows, it does not filter them.
-- Callers (the dashboard and ad-hoc Excel-via-ODBC users on the finance
-- team) decide what subset of the enriched data they want by filtering on
-- IS_STATEMENT_ELIGIBLE, PARTIDA_PL, IS_INTERCOMPANY, etc.
--
-- Replaces in Python: prepare_pnl + filter_for_statements + assign_partida_pl
--   (backend/services/accounting/transforms.py:78-166)
--
-- Output columns:
--   CIA, CUENTA_CONTABLE, DESCRIPCION, NIT, RAZON_SOCIAL,
--   CENTRO_COSTO, DESC_CECO, FECHA, ASIENTO,
--   DEBITO_LOCAL, CREDITO_LOCAL, FUENTE, CONTABILIDAD,
--   SALDO                  DECIMAL(28,8)  -- CREDITO_LOCAL - DEBITO_LOCAL
--   MES                    INT            -- MONTH(FECHA)
--   PARTIDA_PL             VARCHAR(40)    -- 15-rule classification (np.select order)
--   IS_INTERCOMPANY        BIT
--   IS_STATEMENT_ELIGIBLE  BIT            -- 1 = belongs to the P&L statement
--
-- IS_STATEMENT_ELIGIBLE rule (mirrors transforms.filter_for_statements):
--   1 when CAST(LEFT(REPLACE(CUENTA_CONTABLE, '.', ''), 3) AS INT) >= 619
--      AND CUENTA_CONTABLE <> '79.1.1.1.01'
--   0 otherwise (low-prefix inventory accounts like 60.x, 61.x, and the
--   single excluded synthetic 79.1.1.1.01).
--
-- Row-level filters that DO stay in the view (these are correctness, not scope):
--   * Class 6/7/8 accounts only        (PNL_ACCOUNT_PREFIXES)
--   * FUENTE NOT LIKE 'CIERRE%'        (closing entries don't reflect activity)
--
-- Trailing-space safety:
--   ~826k / 8.8M rows store CUENTA_CONTABLE and CENTRO_COSTO with trailing
--   spaces. RTRIM once at the bottom of each per-CIA view.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- Per-company template applied to FIBERLINE / FIBERTECH / NEXTNET / FIBERLUX.
-- Each block is identical except for the schema name and 'CIA' literal.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR ALTER VIEW [FIBERLINE].[VISTA_PNL_PREPARADO] AS
SELECT
    CIA,
    CUENTA_CONTABLE, DESCRIPCION, NIT, RAZON_SOCIAL,
    CENTRO_COSTO, DESC_CECO, FECHA, ASIENTO,
    DEBITO_LOCAL, CREDITO_LOCAL, FUENTE, CONTABILIDAD,

    CAST(CREDITO_LOCAL - DEBITO_LOCAL AS DECIMAL(28, 8)) AS SALDO,
    MONTH(FECHA) AS MES,

    -- PARTIDA_PL — mirrors transforms.py:112-145 (np.select, first match wins)
    CASE
        WHEN CUENTA_CONTABLE IN ('68.9.9.1.01', '68.7.1.1.01')
            THEN 'PROVISION INCOBRABLE'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6')
             AND LEFT(CENTRO_COSTO, 1) IN ('1', '4', '6')
            THEN 'D&A - COSTO'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6')
            THEN 'D&A - GASTO'
        WHEN CUENTA_CONTABLE = '62.2.1.1.04'
            THEN 'PARTICIPACION DE TRABAJADORES'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('67.6', '77.6')
            THEN 'DIFERENCIA DE CAMBIO'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('67', '77')
            THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CUENTA_CONTABLE, 2) = '70'
            THEN 'INGRESOS ORDINARIOS'
        WHEN CUENTA_CONTABLE = '75.9.9.1.01'
            THEN 'INGRESOS PROYECTOS'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('73', '75')
            THEN 'OTROS INGRESOS'
        WHEN LEFT(CUENTA_CONTABLE, 1) = '8'
            THEN 'IMPUESTO A LA RENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '7'
            THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CENTRO_COSTO, 1) IN ('1', '4')
            THEN 'COSTO'
        WHEN LEFT(CENTRO_COSTO, 1) = '2'
            THEN 'GASTO VENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '3'
            THEN 'GASTO ADMIN'
        WHEN LEFT(CENTRO_COSTO, 1) = '5'
            THEN 'OTROS EGRESOS'
        ELSE 'POR CLASIFICAR'
    END AS PARTIDA_PL,

    -- IS_INTERCOMPANY  (transforms.py:149-155)
    CAST(
        CASE
            WHEN CUENTA_CONTABLE IN ('70.1.2.2.01','70.3.3.1.02','70.3.3.1.03','70.3.3.1.04')
                THEN 1
            WHEN CENTRO_COSTO LIKE '%.121.%'
                THEN 1
            ELSE 0
        END
    AS BIT) AS IS_INTERCOMPANY,

    -- IS_STATEMENT_ELIGIBLE  (transforms.filter_for_statements)
    CAST(
        CASE
            WHEN TRY_CAST(LEFT(REPLACE(CUENTA_CONTABLE, '.', ''), 3) AS INT) >= 619
             AND CUENTA_CONTABLE <> '79.1.1.1.01'
                THEN 1
            ELSE 0
        END
    AS BIT) AS IS_STATEMENT_ELIGIBLE

FROM (
    SELECT
        CIA,
        RTRIM(CUENTA_CONTABLE)  AS CUENTA_CONTABLE,
        RTRIM(DESCRIPCION)      AS DESCRIPCION,
        RTRIM(NIT)              AS NIT,
        RTRIM(RAZON_SOCIAL)     AS RAZON_SOCIAL,
        RTRIM(CENTRO_COSTO)     AS CENTRO_COSTO,
        RTRIM(DESC_CECO)        AS DESC_CECO,
        FECHA,
        RTRIM(ASIENTO)          AS ASIENTO,
        DEBITO_LOCAL,
        CREDITO_LOCAL,
        RTRIM(FUENTE)           AS FUENTE,
        CONTABILIDAD
    FROM [FIBERLINE].[VISTA_ANALISIS_CECOS]
    WHERE LEFT(CUENTA_CONTABLE, 1) IN ('6', '7', '8')
      AND FUENTE NOT LIKE 'CIERRE%'
) src;
GO


CREATE OR ALTER VIEW [FIBERTECH].[VISTA_PNL_PREPARADO] AS
SELECT
    CIA, CUENTA_CONTABLE, DESCRIPCION, NIT, RAZON_SOCIAL,
    CENTRO_COSTO, DESC_CECO, FECHA, ASIENTO,
    DEBITO_LOCAL, CREDITO_LOCAL, FUENTE, CONTABILIDAD,
    CAST(CREDITO_LOCAL - DEBITO_LOCAL AS DECIMAL(28, 8)) AS SALDO,
    MONTH(FECHA) AS MES,
    CASE
        WHEN CUENTA_CONTABLE IN ('68.9.9.1.01', '68.7.1.1.01') THEN 'PROVISION INCOBRABLE'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6')
             AND LEFT(CENTRO_COSTO, 1) IN ('1','4','6') THEN 'D&A - COSTO'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6') THEN 'D&A - GASTO'
        WHEN CUENTA_CONTABLE = '62.2.1.1.04' THEN 'PARTICIPACION DE TRABAJADORES'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('67.6','77.6') THEN 'DIFERENCIA DE CAMBIO'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('67','77') THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CUENTA_CONTABLE, 2) = '70' THEN 'INGRESOS ORDINARIOS'
        WHEN CUENTA_CONTABLE = '75.9.9.1.01' THEN 'INGRESOS PROYECTOS'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('73','75') THEN 'OTROS INGRESOS'
        WHEN LEFT(CUENTA_CONTABLE, 1) = '8' THEN 'IMPUESTO A LA RENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '7' THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CENTRO_COSTO, 1) IN ('1','4') THEN 'COSTO'
        WHEN LEFT(CENTRO_COSTO, 1) = '2' THEN 'GASTO VENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '3' THEN 'GASTO ADMIN'
        WHEN LEFT(CENTRO_COSTO, 1) = '5' THEN 'OTROS EGRESOS'
        ELSE 'POR CLASIFICAR'
    END AS PARTIDA_PL,
    CAST(
        CASE
            WHEN CUENTA_CONTABLE IN ('70.1.2.2.01','70.3.3.1.02','70.3.3.1.03','70.3.3.1.04') THEN 1
            WHEN CENTRO_COSTO LIKE '%.121.%' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_INTERCOMPANY,
    CAST(
        CASE
            WHEN TRY_CAST(LEFT(REPLACE(CUENTA_CONTABLE, '.', ''), 3) AS INT) >= 619
             AND CUENTA_CONTABLE <> '79.1.1.1.01' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_STATEMENT_ELIGIBLE
FROM (
    SELECT
        CIA,
        RTRIM(CUENTA_CONTABLE) AS CUENTA_CONTABLE,
        RTRIM(DESCRIPCION) AS DESCRIPCION,
        RTRIM(NIT) AS NIT, RTRIM(RAZON_SOCIAL) AS RAZON_SOCIAL,
        RTRIM(CENTRO_COSTO) AS CENTRO_COSTO, RTRIM(DESC_CECO) AS DESC_CECO,
        FECHA, RTRIM(ASIENTO) AS ASIENTO,
        DEBITO_LOCAL, CREDITO_LOCAL, RTRIM(FUENTE) AS FUENTE, CONTABILIDAD
    FROM [FIBERTECH].[VISTA_ANALISIS_CECOS]
    WHERE LEFT(CUENTA_CONTABLE, 1) IN ('6','7','8')
      AND FUENTE NOT LIKE 'CIERRE%'
) src;
GO


CREATE OR ALTER VIEW [NEXTNET].[VISTA_PNL_PREPARADO] AS
SELECT
    CIA, CUENTA_CONTABLE, DESCRIPCION, NIT, RAZON_SOCIAL,
    CENTRO_COSTO, DESC_CECO, FECHA, ASIENTO,
    DEBITO_LOCAL, CREDITO_LOCAL, FUENTE, CONTABILIDAD,
    CAST(CREDITO_LOCAL - DEBITO_LOCAL AS DECIMAL(28, 8)) AS SALDO,
    MONTH(FECHA) AS MES,
    CASE
        WHEN CUENTA_CONTABLE IN ('68.9.9.1.01', '68.7.1.1.01') THEN 'PROVISION INCOBRABLE'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6')
             AND LEFT(CENTRO_COSTO, 1) IN ('1','4','6') THEN 'D&A - COSTO'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6') THEN 'D&A - GASTO'
        WHEN CUENTA_CONTABLE = '62.2.1.1.04' THEN 'PARTICIPACION DE TRABAJADORES'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('67.6','77.6') THEN 'DIFERENCIA DE CAMBIO'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('67','77') THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CUENTA_CONTABLE, 2) = '70' THEN 'INGRESOS ORDINARIOS'
        WHEN CUENTA_CONTABLE = '75.9.9.1.01' THEN 'INGRESOS PROYECTOS'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('73','75') THEN 'OTROS INGRESOS'
        WHEN LEFT(CUENTA_CONTABLE, 1) = '8' THEN 'IMPUESTO A LA RENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '7' THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CENTRO_COSTO, 1) IN ('1','4') THEN 'COSTO'
        WHEN LEFT(CENTRO_COSTO, 1) = '2' THEN 'GASTO VENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '3' THEN 'GASTO ADMIN'
        WHEN LEFT(CENTRO_COSTO, 1) = '5' THEN 'OTROS EGRESOS'
        ELSE 'POR CLASIFICAR'
    END AS PARTIDA_PL,
    CAST(
        CASE
            WHEN CUENTA_CONTABLE IN ('70.1.2.2.01','70.3.3.1.02','70.3.3.1.03','70.3.3.1.04') THEN 1
            WHEN CENTRO_COSTO LIKE '%.121.%' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_INTERCOMPANY,
    CAST(
        CASE
            WHEN TRY_CAST(LEFT(REPLACE(CUENTA_CONTABLE, '.', ''), 3) AS INT) >= 619
             AND CUENTA_CONTABLE <> '79.1.1.1.01' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_STATEMENT_ELIGIBLE
FROM (
    SELECT
        CIA,
        RTRIM(CUENTA_CONTABLE) AS CUENTA_CONTABLE,
        RTRIM(DESCRIPCION) AS DESCRIPCION,
        RTRIM(NIT) AS NIT, RTRIM(RAZON_SOCIAL) AS RAZON_SOCIAL,
        RTRIM(CENTRO_COSTO) AS CENTRO_COSTO, RTRIM(DESC_CECO) AS DESC_CECO,
        FECHA, RTRIM(ASIENTO) AS ASIENTO,
        DEBITO_LOCAL, CREDITO_LOCAL, RTRIM(FUENTE) AS FUENTE, CONTABILIDAD
    FROM [NEXTNET].[VISTA_ANALISIS_CECOS]
    WHERE LEFT(CUENTA_CONTABLE, 1) IN ('6','7','8')
      AND FUENTE NOT LIKE 'CIERRE%'
) src;
GO


CREATE OR ALTER VIEW [FIBERLUX].[VISTA_PNL_PREPARADO] AS
SELECT
    CIA, CUENTA_CONTABLE, DESCRIPCION, NIT, RAZON_SOCIAL,
    CENTRO_COSTO, DESC_CECO, FECHA, ASIENTO,
    DEBITO_LOCAL, CREDITO_LOCAL, FUENTE, CONTABILIDAD,
    CAST(CREDITO_LOCAL - DEBITO_LOCAL AS DECIMAL(28, 8)) AS SALDO,
    MONTH(FECHA) AS MES,
    CASE
        WHEN CUENTA_CONTABLE IN ('68.9.9.1.01', '68.7.1.1.01') THEN 'PROVISION INCOBRABLE'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6')
             AND LEFT(CENTRO_COSTO, 1) IN ('1','4','6') THEN 'D&A - COSTO'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('68.0','68.1','68.2','68.3','68.4','68.5','68.6') THEN 'D&A - GASTO'
        WHEN CUENTA_CONTABLE = '62.2.1.1.04' THEN 'PARTICIPACION DE TRABAJADORES'
        WHEN LEFT(CUENTA_CONTABLE, 4) IN ('67.6','77.6') THEN 'DIFERENCIA DE CAMBIO'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('67','77') THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CUENTA_CONTABLE, 2) = '70' THEN 'INGRESOS ORDINARIOS'
        WHEN CUENTA_CONTABLE = '75.9.9.1.01' THEN 'INGRESOS PROYECTOS'
        WHEN LEFT(CUENTA_CONTABLE, 2) IN ('73','75') THEN 'OTROS INGRESOS'
        WHEN LEFT(CUENTA_CONTABLE, 1) = '8' THEN 'IMPUESTO A LA RENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '7' THEN 'RESULTADO FINANCIERO'
        WHEN LEFT(CENTRO_COSTO, 1) IN ('1','4') THEN 'COSTO'
        WHEN LEFT(CENTRO_COSTO, 1) = '2' THEN 'GASTO VENTA'
        WHEN LEFT(CENTRO_COSTO, 1) = '3' THEN 'GASTO ADMIN'
        WHEN LEFT(CENTRO_COSTO, 1) = '5' THEN 'OTROS EGRESOS'
        ELSE 'POR CLASIFICAR'
    END AS PARTIDA_PL,
    CAST(
        CASE
            WHEN CUENTA_CONTABLE IN ('70.1.2.2.01','70.3.3.1.02','70.3.3.1.03','70.3.3.1.04') THEN 1
            WHEN CENTRO_COSTO LIKE '%.121.%' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_INTERCOMPANY,
    CAST(
        CASE
            WHEN TRY_CAST(LEFT(REPLACE(CUENTA_CONTABLE, '.', ''), 3) AS INT) >= 619
             AND CUENTA_CONTABLE <> '79.1.1.1.01' THEN 1
            ELSE 0
        END
    AS BIT) AS IS_STATEMENT_ELIGIBLE
FROM (
    SELECT
        CIA,
        RTRIM(CUENTA_CONTABLE) AS CUENTA_CONTABLE,
        RTRIM(DESCRIPCION) AS DESCRIPCION,
        RTRIM(NIT) AS NIT, RTRIM(RAZON_SOCIAL) AS RAZON_SOCIAL,
        RTRIM(CENTRO_COSTO) AS CENTRO_COSTO, RTRIM(DESC_CECO) AS DESC_CECO,
        FECHA, RTRIM(ASIENTO) AS ASIENTO,
        DEBITO_LOCAL, CREDITO_LOCAL, RTRIM(FUENTE) AS FUENTE, CONTABILIDAD
    FROM [FIBERLUX].[VISTA_ANALISIS_CECOS]
    WHERE LEFT(CUENTA_CONTABLE, 1) IN ('6','7','8')
      AND FUENTE NOT LIKE 'CIERRE%'
) src;
GO


-- ─────────────────────────────────────────────────────────────────────────────
-- Umbrella view in REPORTES — matches the existing pattern.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR ALTER VIEW [REPORTES].[VISTA_PNL_PREPARADO] AS
SELECT * FROM [FIBERLINE].[VISTA_PNL_PREPARADO]
UNION ALL
SELECT * FROM [FIBERTECH].[VISTA_PNL_PREPARADO]
UNION ALL
SELECT * FROM [NEXTNET].[VISTA_PNL_PREPARADO]
UNION ALL
SELECT * FROM [FIBERLUX].[VISTA_PNL_PREPARADO];
GO
